kind: pipeline
name: Test mysql:latest
workspace:
    base: /go
    path: src/github.com/LucienShui/PasteMeBackend

services:
- name: mysql
  image: mysql:latest
  ports:
  - 3306
  environment:
    MYSQL_USER: username
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: pasteme

steps:
- name: test
  image: golang:latest
  commands:
  - sleep 15
  - bash dep.sh
  - bash gotest.sh

---

kind: pipeline
name: Test mysql:5
workspace:
  base: /go
  path: src/github.com/LucienShui/PasteMeBackend

services:
  - name: mysql
    image: mysql:5
    ports:
      - 3306
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pasteme

steps:
  - name: test
    image: golang:latest
    commands:
      - sleep 15
      - bash dep.sh
      - bash gotest.sh

---

kind: pipeline
name: Build
workspace:
    base: /go
    path: src/github.com/LucienShui/PasteMeBackend

steps:
- name: build
  image: golang:latest
  commands:
  - bash dep.sh
  - go build -o pastemed
