version: "3"
services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pasteme
    volumes:
      - data:/var/lib/mysql

  nginx:
    image: nginx:1.17.1
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - conf.d:/etc/nginx/conf.d
